package de.greenrobot.daoexample;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.daoexample.CommentToMe;
import de.greenrobot.daoexample.ReplyToMe;

import de.greenrobot.daoexample.CommentToMeDao;
import de.greenrobot.daoexample.ReplyToMeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig commentToMeDaoConfig;
    private final DaoConfig replyToMeDaoConfig;

    private final CommentToMeDao commentToMeDao;
    private final ReplyToMeDao replyToMeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        commentToMeDaoConfig = daoConfigMap.get(CommentToMeDao.class).clone();
        commentToMeDaoConfig.initIdentityScope(type);

        replyToMeDaoConfig = daoConfigMap.get(ReplyToMeDao.class).clone();
        replyToMeDaoConfig.initIdentityScope(type);

        commentToMeDao = new CommentToMeDao(commentToMeDaoConfig, this);
        replyToMeDao = new ReplyToMeDao(replyToMeDaoConfig, this);

        registerDao(CommentToMe.class, commentToMeDao);
        registerDao(ReplyToMe.class, replyToMeDao);
    }
    
    public void clear() {
        commentToMeDaoConfig.getIdentityScope().clear();
        replyToMeDaoConfig.getIdentityScope().clear();
    }

    public CommentToMeDao getCommentToMeDao() {
        return commentToMeDao;
    }

    public ReplyToMeDao getReplyToMeDao() {
        return replyToMeDao;
    }

}
