package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DRAFT".
 */
public class Draft {

    private Long id;
    private String content;
    private java.util.Date create_time;

    public Draft() {
    }

    public Draft(Long id) {
        this.id = id;
    }

    public Draft(Long id, String content, java.util.Date create_time) {
        this.id = id;
        this.content = content;
        this.create_time = create_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public java.util.Date getCreate_time() {
        return create_time;
    }

    public void setCreate_time(java.util.Date create_time) {
        this.create_time = create_time;
    }

}
